name: lab2ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - joblib
  - pip:
      - opencv-python-headless
      - streamlit